# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.7.0"

package:
  name: wire-pipe
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/wire-pipe/wire_pipe-${{ version }}.tar.gz
    sha256: 51eede8bb6a3d82be5080726fff86f7b3a75dd90238e3bd1835dac2e6753a2ca

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - python >=${{ python_min }}
    - wiredb >=0.6.0,<0.7.0

tests:
  - python:
      imports: wire_pipe
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/davidbrochart/wiredb
  summary: Wire for communicating over pipes.

extra:
  recipe-maintainers:
    - davidbrochart
